name: 'synonyms8_appendOrigClassname'
is_two_stage: 0
one_stage:
    prompt_template: 'Please list {num_to_generate:d} noun synonyms of the object "{classname}"'
    num_to_generate: 8
    include_orig_classname: 1
    output_template: '{classname}, also known as a {output}'
